---
- name: reload iptables
  service: name=iptables state=reloaded

- name: restart netfilter-persistent
  service: name=netfilter-persistent state=restarted

- name: restart ip6tables
  service: name=ip6tables state=restarted

