---

ipaccess_template: 'iptables.j2'
lxc_nat_template: 'lxc-nat.j2'
ip_nat: []
is_lxc: false
lxc_net: '10.0.3.0/24'
is_libvirt: false
libvirt_net: '192.168.122.0/24'
is_dnat: true
is_masquerade: false

iptables_file_rhel: "/etc/sysconfig/iptables"
iptables_file_ubuntu: "/etc/iptables/rules.v4"
# iptables_tmp_file - check and validate rules before changing actual firewall
iptables_tmp_file: '/etc/sysconfig/iptables.tmp'

ip6tables_file: '/etc/sysconfig/ip6tables'
is_ipv6_web_server: false
lxc_access_from: []
lxc_containers: []
iplist_ssh_access_hosts: []

# Put your actual ipaccess_default list of the rules, which may be common for all your hosts, into group_vars/all/[ipaccess.yaml]
# You may redifine it at host_vars/ level, or use ipaccess_extended list to customize firewall for paticular host or group.
ipaccess_default:
  - name: 'ssh full access'
    iplist: ['0.0.0.0/0']
    ports: 'ssh'

# May be redifined in group, host or task vars, if neccessary to add more than default rules.
ipaccess_extended: []
