---
- name: Download mysql-exporter
  get_url:
    url: https://github.com/prometheus/mysqld_exporter/releases/download/v{{ mysql_exporter_version }}/mysqld_exporter-{{ mysql_exporter_version }}.linux-amd64.tar.gz
    dest: /tmp/mysqld_exporter-{{ mysql_exporter_version }}.linux-amd64.tar.gz

- name: Unpack mysql-exporter
  unarchive:
    src: /tmp/mysqld_exporter-{{ mysql_exporter_version }}.linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes
    creates: /tmp/mysqld_exporter-{{ mysql_exporter_version }}.linux-amd64/mysqld_exporter

- name: Install mysql-exporter binary
  copy:
    src: /tmp/mysqld_exporter-{{ mysql_exporter_version }}.linux-amd64/mysqld_exporter
    dest: /usr/local/sbin/mysql-exporter
    remote_src: yes
    mode: '0755'

- name: Install systemd unit
  template:
    src: mysql-exporter.service.j2
    dest: /etc/systemd/system/mysql-exporter.service
    mode: '0644'
  notify: restart mysql-exporter

- name: Start mysql-exporter
  systemd:
    name: mysql-exporter
    state: started
    daemon_reload: yes

- name: Enable mysql-exporter
  systemd:
    name: mysql-exporter
    enabled: yes
