---
- name: Set sudo group based on OS family
  set_fact:
    sudo_group: "{{ 'sudo' if ansible_os_family == 'Debian' else 'wheel' }}"
  tags:
   - always

- name: Install iptables
  package: name=iptables state=present
  tags: ['iptables','install']

- name: create /etc/sysconfig directory
  file:
    path: /etc/sysconfig
    state: directory
  tags: ['iptables','iptablestmp']


- name: Merge the two ipaccess lists
  set_fact:
    ipaccess: "{{ ipaccess_default + ipaccess_extended }}"
  tags: ['rules','iptables','iptablestmp']

- name: "temporary iptables file"
  ansible.builtin.template:
    src: "{{ ipaccess_template }}"
    dest: "{{ iptables_tmp_file }}"
    owner: root
    group: "{{ sudo_group }}"
    mode: 0440
    force: yes
    backup: no
  tags: ['rules', 'iptablestmp', 'iptables.tmp', 'iptables']

- name: "Verify iptables.tmp file"
  ansible.builtin.command: "iptables-restore --test {{ iptables_tmp_file }}"
  tags: ['rules', 'iptablestmp', 'iptables.tmp', 'iptables']

- import_tasks: iptables-services.yml
  when: ansible_facts['os_family'] == "RedHat"

- import_tasks: iptables-persistent.yml
  when: ansible_facts['os_family'] == "Debian"

